# Generated by Django 6.0.2 on 2026-02-25 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_city_state_remove_complaint_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='state',
            name='category',
            field=models.CharField(choices=[('Uttar Pradesh', 'Uttar Pradesh'), ('Uttrakhand', 'Uttrakhand'), ('Rajasthan', 'Rajasthan')], default=1, max_length=100),
            preserve_default=False,
        ),
    ]
