# Generated by Django 6.0.2 on 2026-03-02 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_state_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='state',
            name='category',
        ),
    ]
