# Generated by Django 6.0.2 on 2026-03-02 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_state_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
