# Generated by Django 6.0.2 on 2026-03-05 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_scheme_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='area',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
